{% set name = "aws-lambda-powertools" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws_lambda_powertools-{{ version }}.tar.gz
  sha256: 40562847d285ffe6ead6d9e644482a597d5f15e511073b88531e685ee57f3777

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6,<4.0
  run:
    - aws-xray-sdk >=2.5.0,<3.0.0
    - boto3 >=1.12,<2.0
    - python-fastjsonschema >=2.14.5,<3.0.0
    - jmespath >=0.10.0,<0.11.0
    - python >=3.6,<4.0
  run_constrained:
    - pydantic >=1.6.0,<2.0.0
    - typing_extensions >=3.7.4.2,<4.0.0.0

test:
  imports:
    - aws_lambda_powertools
    - aws_lambda_powertools.logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://awslabs.github.io/aws-lambda-powertools-python/
  summary: Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric
  description: |
    A suite of Python utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging,
    custom metrics, and more. ([AWS Lambda Powertools Java](https://github.com/awslabs/aws-lambda-powertools-java) is also available).
  license: MIT-0
  license_family: MIT
  license_file: LICENSE
  doc_url: https://awslabs.github.io/aws-lambda-powertools-python/api/
  dev_url: https://github.com/awslabs/aws-lambda-powertools-python

extra:
  recipe-maintainers:
    - BastianZim
